### ISSUE TITLE
Request for transfer: power-assert-js organization

### ISSUE THREAD

**Issue by twada** [power-assert-js/intelli-espower-loader#12]
Hi @azu, I've created new organization [power-assert-js](https://github.com/power-assert-js) to help users to find related products easily, and I want you to transfer this project to power-assert-js org.

If you agree with me, please see [Transferring a repository](https://help.github.com/articles/transferring-a-repository/) for details. If you do not want to transfer, it's no problem at all ;)

Thanks!

**Comment by azu** [comment]
power-assert-js/intelli-espower-loader :arrow_left: :walking:

**Comment by twada** [comment]
@azu Thank you!!!
