### ISSUE TITLE
not support typescript ?

### ISSUE THREAD

**Issue by zengming00** [power-assert-js/intelli-espower-loader#18]
hi, this is my package.json config
 ```json
"scripts": {
    "test": "mocha -t 5000 --require ts-node/register --require intelli-espower-loader test/*"
  },
```
I tried espower-typescript, but it `only compilerOptions field in tsconfig.json is applied.`
my tsconfig.json is Specify the root directory :  
```
 "rootDir": "./src/"
```
my test code put in "./test/", so i specify tsconfig.json 
```
  "exclude": [
    "test/"
  ]
```
espower-typescript can not compile , I must use `ts-node/register`

and `intelli-espower-loader` not work , How to use it correctly

**Comment by azu** [comment]
TypeScript version is https://github.com/power-assert-js/espower-typescript
